"""add_xp_to_user

Revision ID: dbd00fed5b74
Revises: 3e67b90f089b
Create Date: 2026-01-17 03:37:26.320238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd00fed5b74'
down_revision: Union[str, None] = '3e67b90f089b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET xp = 0")
    op.alter_column('users', 'xp', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    # ### end Alembic commands ###