"""add failed login attempts and locking

Revision ID: eefcc9832520
Revises: 606cd74eec0a
Create Date: 2026-01-26 04:38:28.121993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefcc9832520'
down_revision: Union[str, None] = '606cd74eec0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET failed_login_attempts = 0")
    op.alter_column('users', 'failed_login_attempts', nullable=False)
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###